export const STUDY_OPTIONS = [
  {label: 'Full Time', value: 'Full Time'},
  {label: 'Part Time', value: 'Part Time'},
  {label: 'Blended', value: 'Blended'},
  {label: 'Evening', value: 'Evening'},
  {label: 'Weekend', value: 'Weekend'},
  {label: 'Flexible', value: 'Flexible'},
  {label: 'Other', value: 'Other'},
];

export const STUDY_TIMINGS = [
  {label: '1 Year', value: '1 Year'},
  {label: '2 Years', value: '2 Years'},
  {label: '3 Years', value: '3 Years'},
  {label: '4 Years', value: '4 Years'},
  {label: '5 Years', value: '5 Years'},
  {label: '6 Years', value: '6 Years'},
];

export const STUDY_LOCATIONS = [
  {label: 'On Campus', value: 'On Campus'},
  {label: 'Online', value: 'Online'},
  {label: 'Distance Learning', value: 'Distance Learning'},
  {label: 'Blended', value: 'Blended'},
  {label: 'Flexible', value: 'Flexible'},
  {label: 'Other', value: 'Other'},
];

export const GRADING_SCHEME = [
  {label: 'Percentage', value: 'Percentage'},
  {label: 'GPA', value: 'GPA'},
];

export const EDUCATION_LEVELS = [
  {label: '12-Year High School', value: '12-Year High School'},
  {
    label: '3-Year Bachelors Degree',
    value: '3-Year Bachelors Degree',
  },
  {
    label: '4-Year Bachelors Degree',
    value: '4-Year Bachelors Degree',
  },
  {label: 'Masters Degree', value: 'Masters Degree'},
];

export const INTAKES = [
  {label: 'Jan', value: 'JAN'},
  {label: 'Feb', value: 'FEB'},
  {label: 'Mar', value: 'MAR'},
  {label: 'Apr', value: 'APR'},
  {label: 'May', value: 'MAY'},
  {label: 'Jun', value: 'JUN'},
  {label: 'Jul', value: 'JUL'},
  {label: 'Aug', value: 'AUG'},
  {label: 'Sep', value: 'SEP'},
  {label: 'Oct', value: 'OCT'},
  {label: 'Nov', value: 'NOV'},
  {label: 'Dec', value: 'DEC'},
];

export const TEST_TYPES = [
  {label: 'GRE', value: 'gre'},
  {label: 'GMAT', value: 'gmat'},
  {label: 'IELTS', value: 'ielts'},
  {label: 'TOEFL', value: 'toefl'},
  {label: 'SAT', value: 'sat'},
  {label: 'PTE', value: 'pte'},
  {label: 'Duolingo', value: 'duolingo'},
];

export const RANKINGS = [
  {
    label: 'Academic Ranking of World Universities (ARWU)',
    value: 'Academic Ranking of World Universities (ARWU)',
  },
  {
    label: 'Times Higher Education (THE)',
    value: 'Times Higher Education (THE)',
  },
  {
    label: 'QS World University Rankings',
    value: 'QS World University Rankings',
  },
  {
    label: 'Webometrics Ranking of World Universities',
    value: 'Webometrics Ranking of World Universities',
  },
  {label: 'U.S. News & World Report', value: 'U.S. News & World Report'},
  {label: 'CWTS Leiden Ranking', value: 'CWTS Leiden Ranking'},
  {
    label: 'Center for World University Rankings (CWUR)',
    value: 'Center for World University Rankings (CWUR)',
  },
  {label: 'Nature Index', value: 'Nature Index'},
  {
    label: 'Scimago Institutions Rankings',
    value: 'Scimago Institutions Rankings',
  },
];

export const TYPES_OF_UNIVERSITIES = [
  {label: 'Engineering', value: 'Engineering'},
  {label: 'Research', value: 'Research'},
  {label: 'Technical', value: 'Technical'},
  {label: 'Medical', value: 'Medical'},
  {label: 'Business Schools', value: 'Business Schools'},
  {label: 'Aerospace', value: 'Aerospace'},
  {label: 'Liberal Arts', value: 'Liberal Arts'},
  {label: 'Law', value: 'Law'},
  {label: 'Art and Design', value: 'Art and Design'},
  {label: 'Music Conservatories', value: 'Music Conservatories'},
  {label: 'Agricultural', value: 'Agricultural'},
  {label: 'Comprehensive', value: 'Comprehensive'},
  {label: 'Other', value: 'Other'},
];

export type ProgramsByLevelAndField = {
  [key: string]: {
    [key: string]: string[];
  };
};
const uniProgramsByLevelAndField: ProgramsByLevelAndField = {
  "Bachelor's": {
    Business: [
      'Business Administration (BBA)',
      'Commerce and Marketing',
      'Business Analytics',
      'Entrepreneurship',
      'Marketing',
      'Management',
      'Finance',
      'International Business',
      'Human Resource Management',
      'Accounting',
      'Supply Chain Management',
      'Business Information Systems',
      'Operations Management',
      'Business Law',
      'Real Estate',
      'Hospitality Management',
      'Sports Management',
      'Economics',
      'Business Finance',
      'Business Marketing',
      'Business Strategy',
      'Organizational Leadership',
      'Business Ethics',
      'Business Communication',
      'Business Consulting',
      'Project Management',
      'Risk Management',
      'Retail Management',
      'International Trade',
      'Business Sustainability',
      'Business Intelligence',
      'Business Innovation',
      'Business Entrepreneurship',
    ],
    Engineering: [
      'Mechanical Engineering',
      'Electrical Engineering',
      'Civil Engineering',
      'Chemical Engineering',
      'Aerospace Engineering',
      'Computer Engineering',
      'Environmental Engineering',
      'Biomedical Engineering',
      'Industrial Engineering',
      'Materials Engineering',
      'Petroleum Engineering',
      'Nuclear Engineering',
      'Robotics Engineering',
      'Mechatronics Engineering',
      'Vehicle Engineering',
      'Professional Pilot',
    ],
    'Health Sciences': [
      'Nursing',
      'Nursing and Patient Care (Dietetics)',
      'Nursing and Patient Care (Physiotherapy)',
      'Nursing and Patient Care (Nurse)',
      'Health Care and Disease Prevention (Public Health)',
      'one-tier Medical Degree Programs',
      'Medical Laboratory Science',
      'Radiography',
      'Physiotherapy',
      'Occupational Therapy',
      'Dietetics',
      'Speech-Language Pathology',
      'Health Informatics',
      'Public Health',
      'Health Administration',
    ],
    'Social Sciences': [
      'Sociology',
      'Anthropology',
      'Political Science',
      'International Relations',
      'Economics',
      'Geography',
      'History',
      'Archaeology',
      'Criminology',
      'Social Work',
      'Communication Studies',
      'Media Studies',
      'Gender Studies',
      'Urban Studies',
    ],
    'Fine Arts': [
      'Visual Arts',
      'Graphic Design',
      'Illustration',
      'Photography',
      'Film Studies',
      'Animation',
      'Fashion Design',
      'Interior Design',
      'Music',
      'Theatre Arts',
      'Dance',
      'Creative Writing',
      'Art History',
    ],
    'Computer Science': [
      'Bachelor of Science in Computer Science (BScCS)',
      'Software Engineering',
      'Computer Engineering',
      'Artificial Intelligence',
      'Data Science',
      'Cybersecurity',
      'Information Technology',
      'Computer Graphics',
      'Game Development',
      'Human-Computer Interaction',
      'Computer Networks',
      'Database Systems',
      'Operating Systems',
      'Web Development',
      'Mobile Development',
      'Cloud Computing',
      'Machine Learning',
      'Network Security',
      'Data Analytics',
      'Software Development',
      'Computer Vision',
      'Natural Language Processing',
      'Robotics',
      'Augmented Reality',
      'Virtual Reality',
      'Big Data',
      'Internet of Things',
      'Blockchain Technology',
      'Information Systems',
      'Computer Architecture',
      'Computer Algorithms',
      'Parallel Computing',
    ],
    Psychology: [
      'General Psychology',
      'Cognitive Psychology',
      'Abnormal Psychology',
      'Developmental Psychology',
      'Educational Psychology',
      'Social Psychology',
      'Industrial-Organizational Psychology',
      'Clinical Psychology',
      'Forensic Psychology',
      'Neuropsychology',
      'Health Psychology',
      'Sport Psychology',
      'Behavioral Psychology',
      'Positive Psychology',
      'Child Psychology',
      'Environmental Psychology',
      'Personality Psychology',
      'Experimental Psychology',
      'Psychological Research',
      'Educational Counseling',
      'School Psychology',
      'Geriatric Psychology',
      'Cross-Cultural Psychology',
      'Psychological Assessment',
      'Forensic Assessment',
      'Psychopathology',
      'Behavioral Neuroscience',
      'Psychopharmacology',
      'Community Psychology',
      'Family Counseling',
      'Clinical Research',
    ],
    Education: [
      'Elementary Education',
      'Secondary Education',
      'Special Education',
      'Early Childhood Education',
      'Physical Education',
      'Music Education',
      'Art Education',
      'Language Education',
      'Mathematics Education',
      'Science Education',
      'English and American Studies',
      'Romance Philology and Cultures (French Studies)',
      'Kindergarten Education',
      'Psychology',
    ],
    Architecture: [
      'Architectural Design',
      'Urban Planning',
      'Landscape Architecture',
      'Interior Architecture',
      'Sustainable Design',
      'Building Technology',
      'Historic Preservation',
      'Architectural Theory',
      'Architectural History',
    ],
    Communication: [
      'Journalism',
      'Public Relations',
      'Advertising',
      'Media Studies',
      'Film and Television',
      'Digital Media',
      'Communication Studies',
      'Broadcasting',
      'Corporate Communication',
    ],
    Agricultural: [
      'Food Engineering',
      'Precision Agricultural Engineering',
      'Rural Development Engineering',
    ],
    IT: [
      'Business Informatics',
      'Computer Science',
      'Computer Science Engineering',
    ],
    Music: [
      'Musical Creative Art and Musicology',
      'Classical Performing Arts (Music)',
    ],
    Science: [
      'Biology',
      'Chemistry',
      'Earth Sciences',
      'Geography',
      'Mathematics',
      '​Physics',
    ],
  },

  "Master's": {
    Business: [
      'Master of Business Administration (MBA)',
      'Master of Science in Finance (MSF)',
      'Master of Science in Marketing (MSM)',
      'Master of Science in Management (MSMgmt)',
      'Master of Science in International Business (MSIB)',
      'Master of Accounting (MAcc)',
      'Master of Human Resource Management (MHRM)',
      'Master of Supply Chain Management (MSCM)',
      'Master of Business Analytics (MBA)',
      'Master of Information Systems (MIS)',
      'Master of Entrepreneurship (MEnt)',
      'Master of Real Estate (MRE)',
      'Master of Hospitality Management (MHM)',
      'Master of Sports Management (MSpM)',
      'Master of Project Management (MPM)',
      'Master of Public Administration (MPA)',
      'Master of Economics',
      'Master of Business Finance',
      'Master of Business Law',
      'Master of Strategic Management',
      'Master of Organizational Leadership',
      'Master of Corporate Governance',
      'Master of International Marketing',
      'Master of Business Ethics',
      'Master of Business Consulting',
      'Master of Operations Research',
      'Master of Business Sustainability',
      'Master of Business Intelligence',
      'Master of Business Innovation',
      'Master of Business Ethics',
      'Master of International Economy and Business',
    ],
    Engineering: [
      'Chemical Engineering',
      'Engineering Management',
      'Environmental Engineering',
      'Mechatronical Engineering',
      '​Mechanical Engineering',
      'Urban Systems Engineering',
      'Postgraduate Diploma in Lean Engineer',
      'Postgraduate Diploma in Lean Manager',
      'Postgraduate Diploma in Strategic Engineering and Sustainability Leadership',
    ],
    'Health Sciences': [
      'Complex Rehabilitation',
      'Public Health',
      'Social Work in Health Care',
      'Social Work and Social Economy',
      'For one-tier Medical Degree Programs, please click here!',
    ],

    'Computer Science': [
      'Master of Science in Computer Science (MSCS)',
      'Master of Science in Data Science (MSDS)',
      'Master of Science in Artificial Intelligence (MSAI)',
      'Master of Science in Cybersecurity (MSCY)',
      'Master of Science in Human-Computer Interaction (MSHCI)',
      'Master of Science in Information Systems (MSIS)',
      'Master of Science in Software Engineering (MSSE)',
      'Master of Science in Computer Engineering (MSCE)',
      'Master of Science in Robotics (MSRO)',
      'Master of Science in Computer Graphics (MSCG)',
      'Master of Science in Machine Learning (MSML)',
      'Master of Science in Natural Language Processing (MSNLP)',
      'Master of Science in Quantum Computing (MSQC)',
      'Master of Science in Big Data Analytics',
      'Master of Science in Cloud Computing',
      'Master of Science in High-Performance Computing',
      'Master of Science in Computer Vision',
      'Master of Science in Distributed Systems',
      'Master of Science in Network Security',
      'Master of Science in Software Architecture',
      'Master of Science in Virtual Reality',
      'Master of Science in Augmented Reality',
      'Master of Science in Blockchain Technology',
      'Master of Science in Internet of Things (IoT)',
      'Master of Science in Mobile App Development',
      'Master of Science in Natural Language Understanding',
      'Master of Science in Quantum Machine Learning',
    ],
    Psychology: [
      'Master of Arts in Psychology (MA Psychology)',
      'Master of Science in Psychology (MSc Psychology)',
      'Master of Applied Psychology (MAP)',
      'Master of Science in Clinical Psychology (MSCP)',
      'Master of Education in Counseling Psychology (MEd Counseling Psychology)',
      'Master of Science in Developmental Psychology (MSc Developmental Psychology)',
      'Master of Science in Social Psychology (MSc Social Psychology)',
      'Master of Science in Neuropsychology (MSc Neuropsychology)',
      'Master of Science in Forensic Psychology (MSc Forensic Psychology)',
      'Master of Science in Organizational Psychology (MSc Organizational Psychology)',
      'Master of Science in Cognitive Psychology',
      'Master of Science in Counseling Psychology',
      'Master of Science in Health Psychology',
      'Master of Science in Industrial-Organizational Psychology',
      'Master of Science in Positive Psychology',
      'Master of Science in Sport Psychology',
      'Master of Science in Behavioral Psychology',
      'Master of Science in Educational Psychology',
      'Master of Science in School Psychology',
      'Master of Science in Environmental Psychology',
      'Master of Science in Psychopathology',
      'Master of Science in Forensic Mental Health',
      'Master of Science in Psychotherapy',
      'Master of Science in Rehabilitation Psychology',
      'Master of Science in Psychopharmacology',
    ],
    Agricultural: [
      'Animal Husbandry Engineering',
      'Agricultural Environmental Management Engineering',
      'Agricultural Water Management Engineering',
      'Crop Production Engineering',
      'Food Safety and Quality Engineering',
      'Plant Protection',
      'Rural Development Engineering',
    ],
    Law: ['European and International Business Law- LL.M'],
    Humanities: ['English Studies', 'American Studies'],
    Science: [
      'Applied Mathematics',
      'Biology',
      'Chemistry',
      'Environmental Sciences',
      'Geography',
      'Geoinformatics',
      '​Hydrobiology - Water Quality Management',
      'Molecular Biology',
      'Physics',
    ],
    Music: ['Classical Musical Performance'],
  },
  Doctorate: {
    Business: [
      'Doctor of Business Administration (DBA)',
      'Doctor of Commerce (DCom)',
      'Doctor of Philosophy in Business',
      'Doctor of Management (DMgmt)',
      'Doctor of Leadership (DLeadership)',
      'Doctor of Finance (DFin)',
      'Doctor of Marketing (DMkt)',
      'Doctor of Strategic Management (DSM)',
      'Doctor of Organizational Behavior (DOrgB)',
      'Doctor of Accounting (DAcc)',
      'Doctor of Entrepreneurship (DEnt)',
      'Doctor of Supply Chain Management (DSCM)',
      'Doctor of Human Resource Management (DHRM)',
      'Doctor of Economics (DEcon)',
      'Doctor of International Business (DIB)',
      'Doctor of Corporate Governance (DCG)',
    ],
    'Computer Science': [
      'Doctor of Philosophy in Computer Science (PhD CS)',
      'Doctor of Engineering in Computer Science',
      'Doctor of Technology in Computer Science',
      'Doctor of Computer Science (DCS)',
      'Doctor of Artificial Intelligence (DAI)',
      'Doctor of Data Science (DDS)',
      'Doctor of Cybersecurity (DCyber)',
      'Doctor of Information Systems (DIS)',
      'Doctor of Software Engineering (DSE)',
      'Doctor of Robotics (DRobotics)',
      'Doctor of Computer Graphics (DCG)',
      'Doctor of Machine Learning (DML)',
      'Doctor of Natural Language Processing (DNLP)',
      'Doctor of Quantum Computing (DQC)',
      'Doctor of Network Security (DNS)',
    ],
    Psychology: [
      'Doctor of Philosophy in Psychology (PhD Psych)',
      'Doctor of Psychology (DPsych)',
      'Doctor of Science in Applied Psychology',
      'Doctor of Clinical Psychology (DClinPsych)',
      'Doctor of Counseling Psychology (DCounselingPsych)',
      'Doctor of Educational Psychology (DEdPsych)',
      'Doctor of Social Psychology (DSocialPsych)',
      'Doctor of Developmental Psychology (DDevPsych)',
      'Doctor of Forensic Psychology (DForensicPsych)',
      'Doctor of Industrial-Organizational Psychology (DIOPsych)',
      'Doctor of Health Psychology (DHealthPsych)',
      'Doctor of Neuropsychology (DNeuropsych)',
      'Doctor of Child Psychology (DChildPsych)',
      'Doctor of Sport Psychology (DSportPsych)',
      'Doctor of Community Psychology (DCommPsych)',
    ],
    'Agricultural Sciences': [
      'Animal Science',
      'Doctoral School of Nutrition and Food Sciences',
      'Crop Sciences and Horticulture',
    ],
    'History and Ethnology': [' Human Sciences'],
    'Natural Sciences': [
      'Biology and Environmental Sciences',
      'Chemistry',
      'Earth Sciences',
      'Mathematical and Computational Sciences',
      'Physics',
    ],
    'Social Sciences': [' Legal Studies', ' Management and Business'],

    'Medical, Pharmaceutical and Health Sciences': [
      'Doctoral School of Health Sciences',
      'Doctoral School of Pharmaceutical Sciences',
      'Doctoral School of Molecular Medicine',
      'Doctoral School of Molecular Cell and Immune Biology',
      'Doctoral School of Neurosciences',
      'Doctoral School of Clinical Medicine',
      'Gyula Petrányi Doctoral School of Clinical Immunology and Allergology',
      'Kálmán Laki Doctoral School',
      'Doctoral School of Dental Sciences',
    ],
    'Information Technology': ['Informatics'],
    Humanities: ['English and American Literature', 'English Linguistics'],
  },
  Certificate: {
    Business: [
      'Certificate in Business Administration',
      'Certificate in Accounting',
      'Certificate in Human Resource Management',
      'Certificate in Finance',
      'Certificate in Marketing',
      'Certificate in Project Management',
      'Certificate in Supply Chain Management',
      'Certificate in Entrepreneurship',
      'Certificate in Leadership',
      'Certificate in Business Analytics',
      'Certificate in International Business',
      'Certificate in Risk Management',
      'Certificate in Business Law',
      'Certificate in Organizational Behavior',
      'Certificate in Strategic Management',
      'Certificate in Retail Management',
    ],
    'Computer Science': [
      'Certificate in Computer Science',
      'Certificate in Software Development',
      'Certificate in Web Development',
      'Certificate in Data Science',
      'Certificate in Cybersecurity',
      'Certificate in Information Technology',
      'Certificate in Network Administration',
      'Certificate in Database Management',
      'Certificate in Artificial Intelligence',
      'Certificate in Mobile App Development',
      'Certificate in Cloud Computing',
      'Certificate in UI/UX Design',
      'Certificate in Game Development',
      'Certificate in IT Project Management',
      'Certificate in IT Support',
    ],
    Psychology: [
      'Certificate in Applied Psychology',
      'Certificate in Counseling',
      'Certificate in Social Work',
      'Certificate in Behavioral Psychology',
      'Certificate in Cognitive Psychology',
      'Certificate in Child Psychology',
      'Certificate in Forensic Psychology',
      'Certificate in Marriage and Family Therapy',
      'Certificate in Substance Abuse Counseling',
      'Certificate in Mental Health Counseling',
      'Certificate in School Psychology',
      'Certificate in Geriatric Psychology',
      'Certificate in Positive Psychology',
      'Certificate in Trauma Counseling',
      'Certificate in Group Therapy',
      'Certificate in Crisis Intervention',
    ],
  },
};
export const uniProgramsByLevelAndFieldJson = JSON.stringify(
  uniProgramsByLevelAndField,
);
